name: Keep Render Service Awake

on:
  schedule:
    # Every 15 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch: # lets you manually trigger it too

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl the Render URL
        run: |
          curl -sSf https://the-globetrotter-challenge-lt1n.onrender.com/ || echo "Ping failed"
